#!/bin/sh

echo "Operating system: $(cat /etc/os-release | grep -w ID | cut -d '=' -f 2)"

#Delete previous resume
rm -f resume 

#Collect PID of running process, without taking process generated by the following command 
ps aux | awk '{print $2}'| tail -n +2  | head -n -5 > pid.list
echo "Collecting informations about running process"
echo "Number of process detected $(cat pid.list | wc -l )"


echo '--------------------------------------' >> resume
echo '----------[OPERATING SYSTEM]----------' >> resume
echo '\n' >>resume
cat /etc/os-release >> resume
echo '\n' >>resume
 
count=0
while read pid
do
	count=$(expr $count + 1)	
	echo "$count) Processing process PID: $pid"
	#Display pid and the command of the process in a header
	echo '--------------------------------------' >> resume
	echo '----------------[PID]-----------------' >> resume
	pmap $pid | head -n +1 >> resume
	
	#Collect shared object (so) used by the process
	pmap $pid | awk '{print $4}' | grep .so | sort -u | uniq >> sobis.list
	
	while read line
	do 
		find / -name $line >> so.list
	done < sobis.list
	

	#Search shared object dependencies
	[ -e so.list ] && while read line  
	do 
		
		#DEBIAN or UBUNTU or CENTOS
		if 
		cat /etc/os-release | grep -q 'ubuntu' ||
		cat /etc/os-release | grep -q 'debian' ||
		cat /etc/os-release | grep -q 'centos' 
		then
			ldd $line | cut -d '>' -f 2 | rev | cut -c 21- | rev |tail -n +2 | head -n -1 >> sotree.list			
		fi
		
		#ALPINE
		if cat /etc/os-release | grep -q 'alpine'; then
			ldd $line | cut -d '>' -f 2 | rev | cut -c 17- | rev |tail -n +2 | head -n -1 >> sotree.list
		fi
		
		
		
	done < so.list
	[ -e so.list ] && cat so.list | sort -u >> package.list
	[ -e sotree.list ] && cat sotree.list | sort -u >> package.list 
	
	#Sort shared objects between those from OS packages and those from non-OS packages
	[ -e package.list ] && while read line 
	do
		#DEBIAN or UBUNTU
		if 
		cat /etc/os-release | grep -q 'ubuntu' ||
		cat /etc/os-release | grep -q 'debian'
		then
			dpkg -S $line >> tmpOS.list 2>> tmpnonOS.list			
		fi
	
		#ALPINE
		if cat /etc/os-release | grep -q 'alpine'
		then
			apk info -W $line >> tmpOS.list 2>> tmpnonOS.list
		fi
		
		#CENTOS
		if cat /etc/os-release | grep -q 'centos'
		then
			rpm -qf $line >> tmpOS.list 2>> tmpnonOS.list
		fi
		
		
	done < package.list
	[ -e tmpOS.list ] && cat tmpOS.list | sort -u >> OS.list
	[ -e tmpnonOS.list ] && cat tmpnonOS.list| sed -e 's/.\{43\}//' | uniq | sort -u >> nonOS.list

	#List of packages in two sections
	echo '--------------------------------------' >> resume
	echo '------------[OS PACKAGES]-------------' >> resume
	[ -e OS.list ] && cat OS.list >> resume
	echo '--------------------------------------' >> resume
	echo '----------[NON_OS PACKAGES]-----------' >> resume
	[ -e nonOS.list ] && cat nonOS.list >> resume 
	echo '\n \n \n' >> resume 

	#Delete tempory files
	rm -f sobis.list OS.list nonOS.list tmpOS.list tmpnonOS.list package.list sotree.list so.list 

done < pid.list

#Delete tempory files
rm -f pid.list

