#!/bin/sh

	#Delete previous report
	rm -f report

	#Collect PID of running process, without taking process generated by the following command 
	ps aux | awk '{print $2}'| tail -n +2  | head -n -5 > pid.list
	echo "Collecting informations about running process"
	echo "Number of process detected $(cat pid.list | wc -l )"

	#Display OS informations in the report
	echo '--------------------------------------' >> report
	echo '----------[OPERATING SYSTEM]----------' >> report
	echo '\n' >>report
	cat /etc/os-release >> report
	echo '\n' >>report
 
	countpid=0
	while read pid
	do

		countpid=$(expr $countpid + 1)	
		echo "$countpid) Processing process PID: $pid"
	
	
		#Display pid and the command of the process in a header
		echo '--------------------------------------' >> report
		echo '----------------[PID]-----------------' >> report
		pmap $pid | head -n +1 >> report
	
		#Collect shared object (so) used by the process
		pmap $pid | awk '{print $4}' | grep .so | sort -u | uniq >> sobis.list
		while read line
		do 
			find / -name $line >> so.list
		done < sobis.list
	

		#Search shared object dependencies
		[ -e so.list ] && while read line  
		do 
			ldd $line | cut -d '>' -f 2 | rev | cut -c 21- | rev |tail -n +2 | head -n -1 >> sotree.list			
		done < so.list
		[ -e so.list ] && cat so.list | sort -u >> package.list
		[ -e sotree.list ] && cat sotree.list | sort -u >> package.list 
	
	
		#Sort shared objects between those from OS packages and those from non-OS packages
		[ -e package.list ] && while read line 
		do
			dpkg -S $line >> tmpOS.list 2>> tmpnonOS.list			
		done < package.list
		[ -e tmpOS.list ] && cat tmpOS.list | sort -u >> OS.list
		[ -e tmpnonOS.list ] && cat tmpnonOS.list| sed -e 's/.\{43\}//' | uniq | sort -u >> nonOS.list

		
		#List of packages in two sections
		echo '--------------------------------------' >> report
		echo '------------[OS PACKAGES]-------------' >> report
		[ -e OS.list ] && cat OS.list >> report
		echo '--------------------------------------' >> report
		echo '----------[NON_OS PACKAGES]-----------' >> report
		[ -e nonOS.list ] && cat nonOS.list >> report 
		echo '\n \n \n' >> report 

		#Delete tempory files
		rm -f sobis.list OS.list nonOS.list tmpOS.list tmpnonOS.list package.list sotree.list so.list 

	done < pid.list

	#Delete tempory files
	rm -f pid.list
